apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-stable
  labels:
    app: flask-app
    track: stable
spec:
  replicas: 5
  selector:
    matchLabels:
      app: flask-app
      track: stable
  template:
    metadata:
      labels:
        app: flask-app
        track: stable
    spec:
      containers:
        - name: flask-app
          image: legionalac/my-flask-image:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ENVIRONMENT
              value: stable
            - name: GREETING
              value: Stable Version - Hello, World!
          ports:
            - containerPort: 4000
          readinessProbe:
            httpGet:
              path: /
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 20
