apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-canary
  labels:
    app: flask-app
    track: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
      track: canary
  template:
    metadata:
      labels:
        app: flask-app
        track: canary
    spec:
      containers:
        - name: flask-app
          image: legionalac/my-flask-image:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ENVIRONMENT
              value: canary
            - name: GREETING
              value: Canary Version - New Features!
          ports:
            - containerPort: 4000
          readinessProbe:
            httpGet:
              path: /
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 20
