apiVersion: v1
kind: Service
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  selector:
    app: flask-app
  ports:
    - name: http
      port: 80
      targetPort: 4000
      nodePort: 30080
  type: NodePort
